print('{:<8}{:<6}{:<10}'.format('hello','world','python'))
str1='heLLlo Good morning'
print(str1.capitalize())
print(str1.lower())
print(str1.isupper())
print(str1.islower())
print(str1.isalpha())
print(str1.isdigit())
print(str1.index('e'))
print(str1.upper())
print(str1.count('l'))
print(str1.replace('morning','afternoon'))
print(str1.center(20))
print(str1.lstrip())
print(str1.rstrip())
print(str1.strip())
print(str1.startswith('h'))