s={1,2,3,4,9}
s1={1,2,3,4,5,6,7,8}
print(s.difference(s1))
# print(s1.difference(s))
print(s.intersection(s1))
# print(s.isdisjoint(s1))
# print(s.issubset(s1))
# print(s.issuperset(s1))
print(s.union(s1))
print(s.symmetric_difference(s1))
# s.copy()
# s1.copy()
# s.difference_update(s1)
# print(s)
s.intersection_update(s1)
print(s)
s.symmetric_difference_update(s1)
print(s)